### ISSUE TITLE
Connect to actual robot

### ISSUE THREAD

**Issue by scottrpaterson** [rakutentech/dorna_arm_ros#3]
How do you use this to actually control the Dorna robot?

I can open "rosrun dorna_nodes dorna_moveit_gazebo.py" and plan movement but how do I actually get it to connect?

I tried opening another command prompt and connecting there using the normal python robot.connect() but that doesn't seem to help either.

When I'm in RViz under MotionPlanning -> Planning and I click Execute I just get failed.

Any help would be greatly appreciated!

**Comment by mfogelson** [comment]
Just saw this I am so sorry.

The gazebo simulation is not connected to the actual robot.  If you want to move the actual robot then you should run:
```
roslaunch dorna_ros.launch
```

This is in the dorna_ros package

**Comment by mfogelson** [comment]
Moveit is not directly connected to the robot, it provides a trajectory to the DornaRos object in dorna_ros_node.py and then re-formats that ros message to a dorna message in dorna_cmd_utils.py. This message is then actually executed in dorna_robot.py which interfaces with the API.

**Comment by scottrpaterson** [comment]
@mfogelson I think I got a bit further. Now I am getting the error: ABORTED: Solution found but controller failed during execution, when I try and Execute a MotionPlanning event. However I only get this far after running  roslaunch dorna_gazebo dorna.launch. When running  roslaunch dorna_ros dorna_ros.launch, the motion library doesn't load. 

I feel like something is missing in the repo. Could you reupload your working files? Or perhaps post a YouTube video showing how to set this up correctly. I've tried about 100 different ways and I keep running into errors.

I'd be happy to pay you if you can help me get this working! Thanks.

**Comment by mfogelson** [comment]
Hey Scott, 

I am happy to jump on a zoom call to further discuss this problem with you in real time.  

Please send me an email at mfogelson630@gmail.com so that we can debug your situation. 

Best, 

mitch
